from typing import Dict, List


SYMPTOM_CATEGORIES: Dict[str, str] = {
    "S1": "Emotional Symptom",
    "S2": "Physical Symptom",
    "S3": "Mind Symptom",
    "S4": "Attitude Symptom",
}


SYMPTOMS: Dict[str, str] = {
    "G01": "Speaking less smoothly",
    "G02": "Rigid and inflexible",
    "G03": "Selfish",
    "G04": "Unstable emotional disturbance",
    "G05": "Respiratory disturbances, shortness of breath",
    "G06": "Diet disorders",
    "G07": "Mindset disorder",
    "G08": "Insomnia",
    "G09": "Want to kill yourself",
    "G10": "Loss of memory",
    "G11": "Antisocial",
    "G12": "Doing a job/activity over and over again",
    "G13": "Experiencing convulsions",
    "G14": "Maintain excessive hygiene",
    "G15": "Indigestion",
    "G16": "Feeling heavy on the limbs",
    "G17": "Excessive suspicion",
    "G18": "Feeling low self-esteem",
    "G19": "Feeling worried about excessive disease",
    "G20": "Feeling weak and tired easily",
    "G21": "Feeling suffering from a severe illness",
    "G22": "Feeling body parts pain",
    "G23": "Feeling hopeless",
    "G24": "Feel very sinful",
    "G25": "Feeling very guilty / very afraid to make mistakes",
    "G26": "Feel very excited",
    "G27": "Feel very smart in a particular field",
    "G28": "Feel very afraid of certain objects/conditions",
    "G29": "Excessive sadness",
    "G30": "Feel happy after pulling hair",
    "G31": "Feel happy to grab an eye-catching object",
    "G32": "Fear of excessive",
    "G33": "Fearing excessive dirty",
    "G34": "Feeling not confident",
    "G35": "Feeling never guilty",
    "G36": "Easy to sweat cold",
    "G37": "Easy to panic",
    "G38": "Easily offended",
    "G39": "Underwent traumatic / violent",
    "G40": "Feeling stressed for one thing",
    "G41": "Always think badly",
    "G42": "Nice to quarrel, hostile and often screwed up",
    "G43": "Nice to interfere in other people's business",
    "G44": "Often lie",
    "G45": "Often counts in the mind",
    "G46": "Often thinking is unrealistic",
    "G47": "often being attentive",
    "G48": "Frequent delusions",
    "G49": "Often shaking",
    "G50": "Frequent hallucinations",
    "G51": "Often angry / irritable",
    "G52": "Often check the body for mild problems",
    "G53": "Often crying hysterically",
    "G54": "Often pull hair until it fall out",
    "G55": "Often experience of loss of physical function, suddenly paralyzed, feeling deaf, blind, numb but only briefly",
    "G56": "Often have severe cramps",
    "G57": "Often experience significant mood swings, very happy to be very sad / vice versa",
    "G58": "Often experience pain / health problems",
    "G59": "Often hurt yourself",
    "G60": "Often feel neglected and inattentive",
    "G61": "Often feel uneasy",
    "G62": "Often feel anxious, restless and daydreaming",
    "G63": "Often feel heart palpitations",
    "G64": "Often feel headache",
    "G65": "Often happy, excessively cheerful",
    "G66": "Often feel tense and anxious",
    "G67": "Often feel depressed with the circumstances",
    "G68": "lost consciousness",
    "G69": "impatient",
    "G70": "difficult to speak normally",
    "G71": "Difficult concentration and decreased memory",
    "G72": "Unable to adjust / difficult to adjust",
    "G73": "Do not have a sense of humor",
    "G74": "Never fear",
}


SOLUTIONS: Dict[str, str] = {
    "T01": "Hospitalization",
    "T02": "Psychoanalysis psychotherapy approach Cognitive Behavioral Therapy (CBT)",
    "T03": "Individual Psychotherapy",
    "T04": "Group psychotherapy",
    "T05": "Environmental psychotherapy",
    "T06": "Supportive psychotherapy",
    "T07": "Relaxing training",
    "T08": "PHBS Technique",
    "T09": "Sports Therapy",
    "T10": "Cognitive behavioral therapy",
}


DISEASES: Dict[str, str] = {
    "P01": "Ansietas Cemas",
    "P02": "Anorexia Nervosa",
    "P03": "Bipolar Disorder",
    "P04": "Conversion Disorder",
    "P05": "Depresi",
    "P06": "Enosimania",
    "P07": "Fobia",
    "P08": "Hipokondria",
    "P09": "Hysteria",
    "P10": "Multiple personality",
}


INITIAL_CASES: List[dict] = [
    {
        "disease_code": "P02",
        "disease_name": DISEASES["P02"],
        "symptom_weights": {"G06": 3, "G32": 3, "G34": 3, "G58": 3},
        "notes": "Ejemplo de Anorexia Nervosa del paper",
    },
    {
        "disease_code": "P01",
        "disease_name": "Anxiety",
        "symptom_weights": {
            "G15": 3,
            "G36": 1,
            "G37": 5,
            "G40": 1,
            "G49": 1,
            "G61": 3,
            "G64": 1,
        },
        "notes": "Ejemplo de Anxiety del paper",
    },
]
